export * from './AuthService';
export *  from './BaseApi';
export * from './CourseService';
export * from './CourseModuleService';
export * from './GrapesjsService';
//export * from  './SettingService';
export * from  './SecurityQuestionService';
export * from './QuizzesService';
export *  from  './AddOnsService';
export * from './UserAuthService';
export * from './UserCourseService';
export * from './UserModuleService';
export * from './UserTableofContentService';
export * from './UserSecurityQuestionService';
export * from './CouponService'
export * from './DashboardService'
export * from './ReferenceService'
