export * from "./Admin/Login";
export * from "./Admin/Navigationbar";
export * from "./Admin/Home";
export * from "./Admin/Sidebar";
export * from "./Admin/Setting";
export * from "./Admin/Courses/CourseModule";
export * from "./Admin/Courses/CourseCreation";
export * from "./Admin/Courses/CourseList";
export * from "./Admin/Courses/CourseAccordion";
export * from "./Admin/Courses/EditCourseAccordion";
export * from "./Admin/Courses/PreviewCourse";
export * from "./Admin/Courses/PreviewQuiz";
export * from "./Admin/Courses/PreviewSecurity";
export * from "./Admin/Courses/PreviewTypingDna";
export * from "./Admin/H5PInteractive/H5PInteractive";
export * from "./Admin/Security";
export * from "./Admin/UserList";
export * from "./Admin/Quiz/AddQuiz";
export * from "./Admin/Quiz/QuizCreation";
export * from "./Admin/Quiz/QuizList";
export * from "./Admin/Payment";
export * from "./Admin/AddOns";
export * from "./Admin/AdminProfile";
export * from "./Admin/ChangePassword";
export * from "./Admin/ForgotPassword";
export * from "./Admin/EnterOtp";
export * from "./Admin/NewPassword";
export * from "./Admin/AppSetting";
export * from './Admin/Coupon'

//User

export * from "./User/TopBar/TopBar";
export * from "./User/Header/Header";
export * from "./User/SignIn/SignIn";
export * from "./User/TypingDna/TypingDna";

export * from "./User/ForgetPassword/ForgetPassword";
export * from "./User/Otp/Otp";
export * from "./User/CreateNewPassword/CreateNewPassword";
export * from "./User/PasswordReset/PasswordReset";
export * from "./User/Module/Module";
export * from "./User/CourseDashboard/CourseDashboard";
export * from "./User/Profile/Profile";
export * from './User/TypingDna'
export * from "./User/TableOfContent/TableOfContent";
export * from "./User/UserSecurityQuestion/UserSecurityQuestion";
export * from "./User/UserQuiz/UserQuiz";
export * from "./User/SuccessfullPayment";
export * from "./User/SetupSecurityQuestion"
export * from "./User/RegisterUser";
export * from "./User/CourseComplete";
export * from "./User/PaymentFailed";
export * from "./User/PaymentCancel"
export * from './User/Reference'