export const ADD_ONS_LIST_SUCCESS = "ADD_ONS_LIST_SUCCESS";
export const ADD_ONS_ADD_SUCCESS = "ADD_ONS_ADD_SUCCESS";
export const ADD_ONS_UPDATE_SUCCESS = "ADD_ONS_UPDATE_SUCCESS";
export const ADD_ONS_GETBYID_SUCCESS = "ADD_ONS_GETBYID_SUCCESS";
export const ADD_ONS_DELETE_SUCCESS = "ADD_ONS_DELETE_SUCCESS";


