export const COUPON_LIST_SUCCESS = "COUPON_LIST_SUCCESS";
export const COUPON_ADD_SUCCESS = "COUPON_ADD_SUCCESS";
export const COUPON_UPDATE_SUCCESS = "COUPON_UPDATE_SUCCESS";
export const COUPON_GETBYID_SUCCESS = "COUPON_GETBYID_SUCCESS";
export const COUPON_DELETE_SUCCESS = "COUPON_DELETE_SUCCESS";
export const PROMOCODE_LIST_SUCCESS = "PROMOCODE_LIST_SUCCESS"