export const GET_REGISTERED_USER_SUCCESS = 'GET_REGISTERED_USER_SUCCESS'
export const GET_COMPLETED_COURSES_SUCCESS = 'GET_COMPLETED_COURSES_SUCCESS'
export const GET_ENROLLED_COURSES_SUCCESS = 'GET_ENROLLED_COURSES_SUCCESS';
export const GET_TOTAL_COURSES_PAYMENT_SUCCESS = 'GET_TOTAL_COURSES_PAYMENT_SUCCESS';
export const GET_USERS_WITH_NO_PAYMENT_SUCCESS = 'GET_USERS_WITH_NO_PAYMENT_SUCCESS'
export const GET_COURSE_PERFORMANCE_SUCCESS = 'GET_COURSE_PERFORMANCE_SUCCESS'