export const GRAPESJS_GETBYID_SUCCESS  = 'GRAPESJS_GETBYID_SUCCESS';
export const GRAPESJS_ADD_SUCCESS      = 'GRAPESJS_ADD_SUCCESS';
export const GRAPESJS_UPDATE_SUCCESS    = 'GRAPESJS_UPDATE_SUCCESS';
export const GRAPESJS_UPDATE_METADATA_SUCCESS   = 'GRAPESJS_UPDATE_METADATA_SUCCESS';
export const GRAPESJS_UPLOAD_ASSETS_SUCCESS     = 'GRAPESJS_UPLOAD_ASSETS_SUCCESS'; 
export const GRAPESJS_GET_ASSETS_SUCCESS     = 'GRAPESJS_GET_ASSETS_SUCCESS';
export const H5P_GET_ALL_SUCCESS    = 'H5P_GET_ALL_SUCCESS'; 