export const QUIZ_DETAIL_LIST_SUCCESS = "QUIZ_DETAIL_LIST_SUCCESS";
export const QUIZ_ADD_SUCCESS = "QUIZ_ADD_SUCCESS";
export const QUIZ_UPDATE_SUCCESS = "QUIZ_UPDATE_SUCCESS";
export const QUIZ_GETBYID_SUCCESS = "QUIZ_GETBYID_SUCCESS";
export const QUIZ_DELETE_SUCCESS = "QUIZ_DELETE_SUCCESS";
export const QUIZ_STATUS_UPDATE_SUCCESS = "QUIZ_STATUS_UPDATE_SUCCESS";
export const QUIZ_CONTAIN_DETAIL = "QUIZ_CONTAIN_DETAIL"
export const CLEAR_QUIZE_REDUCER = "CLEAR_QUIZE_REDUCER"

