export const SECURITY_QUESTION_DETAIL_LIST_SUCCESS = "SECURITY_QUESTION_DETAIL_LIST_SUCCESS";
export const SECURITY_QUESTION_ADD_SUCCESS = "SECURITY_QUESTION_ADD_SUCCESS";
export const SECURITY_QUESTION_UPDATE_SUCCESS = "SECURITY_QUESTION_UPDATE_SUCCESS";
export const SECURITY_QUESTION_GETBYID_SUCCESS = "SECURITY_QUESTION_GETBYID_SUCCESS";
export const SECURITY_QUESTION_DELETE_SUCCESS = "SECURITY_QUESTION_DELETE_SUCCESS";
export const SECURITY_QUESTION_STATUS_UPDATE_SUCCESS = "SECURITY_QUESTION_STATUS_UPDATE_SUCCESS";

