export const CREATE_CHECKOUT_SUCCESS = "CREATE_CHECKOUT_SUCCESS";
export const RECEIPT_SUCCESS = "RECEIPT_SUCCESS";
export const USER_PAYMENT_STATUS_CHECK_SUCCESS = "USER_PAYMENT_STATUS_CHECK_SUCCESS";