export const GET_QUOTES_DETAIL_SUCCESS = 'GET_QUOTES_DETAIL_SUCCESS'
export const TYPING_DNA_SAVE_SUCCESS = 'TYPING_DNA_SAVE_SUCCESS'
export const TYPING_DNA_VERIFY_SUCCESS = "TYPING_DNA_VERIFY_SUCCESS";
export const CHECK_USER_SUCCESS = "CHECK_USER_SUCCESS";
export const TYPING_DNA_SESSION_VERIFIED_USER_SUCCESS = "TYPING_DNA_SESSION_VERIFIED_USER_SUCCESS"