export const COURSE_GET_SUCCESS = 'COURSE_GET_SUCCESS';
export const COURSE_DETAIL_SUCCESS = 'COURSE_DETAIL_SUCCESS';
export const COURSE_DETAIL_BY_ID_SUCCESS = 'COURSE_DETAIL_BY_ID_SUCCESS';
export const COURSE_NAME_AND_AMOUNT_SUCCESS = 'COURSE_NAME_AND_AMOUNT_SUCCESS'