export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_PROFILE_UPDATE_DETAIL_SUCCESS = 'USER_PROFILE_UPDATE_DETAIL_SUCCESS';
export const GET_PROFILE_USER_BY_TOKEN = 'GET_PROFILE_USER_BY_TOKEN';
export const CHANGE_USER_PASSWORD_SUCCESS = 'CHANGE_USER_PASSWORD_SUCCESS';