export const TABLE_OF_CONTENT_GET_SUCCESS           = "TABLE_OF_CONTENT_GET_SUCCESS";
export const TABLE_OF_CONTENT_COURSE_INFO_GET_SUCCESS = "TABLE_OF_CONTENT_COURSE_INFO_GET_SUCCESS";
export const TABLE_OF_CONTENT_CONTAIN_ID            = "TABLE_OF_CONTENT_CONTAIN_ID";
export const TABLE_OF_CONTENT_LIST_SUCCESS          = "TABLE_OF_CONTENT_LIST_SUCCESS";
export const TABLE_OF_CONTENT_QUIZ_DETAIL_ID        = 'TABLE_OF_CONTENT_QUIZ_DETAIL_ID';
export const TABLE_OF_CONTENT_SECURITY_ID           = 'TABLE_OF_CONTENT_SECURITY_ID';
