export const COURSE_MODULE_GET_SUCCESS = 'COURSE_MODULE_GET_SUCCESS';
export const COURSE_MODULE_SECURITY_GET_SUCCESS = 'COURSE_MODULE_GET_SUCCESS';
export const COURSE_MODULE_QUIZ_GET_SUCCESS = 'COURSE_MODULE_GET_SUCCESS';
export const H5P_PLAY_GET_SUCCESS   = 'H5P_PLAY_GET_SUCCESS';
export const QUIZ_MODULE_GET_SUCCESS = 'QUIZ_MODULE_GET_SUCCESS';

